pool:
  vmImage: 'ubuntu-16.04'

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: make setup
    displayName: Setup tools
  - script: make generate
    displayName: Generate bindings
  - script: make package
    displayName: Build package
  - script: make examples
    displayName: Build examples
